import { AlertTriangle, ChevronLeft, ChevronRight, LoaderCircle, SearchX } from "lucide-react";
import type { ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export function Card({ children, className, style }: { children: ReactNode; className?: string; style?: React.CSSProperties }) { return <section className={cn("rounded-lg border border-border bg-card shadow-card", className)} style={style}>{children}</section>; }
export function CardHead({ title, subtitle, action }: { title: string; subtitle?: string; action?: ReactNode }) { return <header className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-3 border-b border-border px-5 py-4"><div className="min-w-0"><h2 className="font-display text-base font-semibold">{title}</h2>{subtitle && <p className="mt-0.5 text-xs text-muted-foreground">{subtitle}</p>}</div>{action}</header>; }
export function PageIntro({ title, description, actions }: { title: string; description: string; actions?: ReactNode }) { return <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end"><div><h2 className="font-display text-2xl font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</div>; }
export function StatusBadge({ children, tone = "neutral" }: { children: ReactNode; tone?: "success"|"warning"|"danger"|"neutral"|"info" }) { return <span className={cn("inline-flex items-center gap-1.5 rounded-full px-2 py-1 text-xs font-medium", {"bg-success-soft text-success":tone==="success","bg-warning-soft text-warning-foreground":tone==="warning","bg-destructive-soft text-destructive":tone==="danger","bg-muted text-muted-foreground":tone==="neutral","bg-info-soft text-info":tone==="info"})}><span className="size-1.5 rounded-full bg-current"/>{children}</span>; }
export function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-1.5 text-xs font-medium text-muted-foreground"><span>{label}</span>{children}</label>; }
export const inputClass = "h-9 w-full rounded-md border border-input bg-background px-3 text-sm text-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15 disabled:cursor-not-allowed disabled:opacity-50";
export function TableWrap({ children }: { children: ReactNode }) { return <div className="overflow-x-auto no-scrollbar"><table className="w-full text-sm">{children}</table></div>; }
export const Th = ({ children, className }: { children: ReactNode; className?: string }) => <th className={cn("border-b border-border bg-muted/45 px-3 py-2 text-left text-[10px] font-semibold uppercase tracking-wider text-muted-foreground", className)}>{children}</th>;
export const Td = ({ children, className }: { children: ReactNode; className?: string }) => <td className={cn("border-b border-border px-3 py-2.5 text-foreground/80", className)}>{children}</td>;
export function Pagination() { return <div className="flex items-center justify-between px-4 py-3 text-xs text-muted-foreground"><span>Showing 1–5 of 24</span><div className="flex gap-1"><Button variant="outline" size="icon" disabled aria-label="Previous page"><ChevronLeft/></Button><Button variant="outline" size="icon" aria-label="Next page"><ChevronRight/></Button></div></div>; }
export function EmptyState() { return <div className="grid min-h-48 place-items-center p-8 text-center"><div><SearchX className="mx-auto size-7 text-muted-foreground"/><p className="mt-3 text-sm font-medium">No matching records</p><p className="mt-1 text-xs text-muted-foreground">Try adjusting your filters.</p></div></div>; }
export function LoadingState() { return <div className="flex min-h-40 items-center justify-center gap-2 text-sm text-muted-foreground"><LoaderCircle className="size-4 animate-spin"/>Loading records…</div>; }
export function ErrorState() { return <div className="flex min-h-40 items-center justify-center gap-2 text-sm text-destructive"><AlertTriangle className="size-4"/>Records could not be loaded.</div>; }