"use client";

import { useState } from "react";
import { CalendarDays, Download, FileText, Plus, Save, Search, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Card, CardHead, Field, PageIntro, Pagination, StatusBadge, TableWrap, Td, Th, inputClass } from "@/components/admin-ui";

const FilterBar = ({ fields }: { fields: string[] }) => <Card className="mb-4 p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">{fields.map((f,i)=><Field key={f} label={f}>{i<2?<input className={inputClass} placeholder={`Enter ${f.toLowerCase()}`} />:<select className={inputClass}><option>All</option><option>Confirmed</option><option>Pending</option></select>}</Field>)}<div className="flex items-end gap-2"><Button><Search/>Search</Button><Button variant="outline" size="icon" aria-label="More filters"><SlidersHorizontal/></Button></div></div></Card>;

const rows = [
 ["BK-10245","Rahul Kumar","Grand Palace Hotel","Deluxe Room","20–22 Sep","2","₹10,620","Paid","Confirmed"],
 ["BK-10244","Priya Seshadri","Azure Residency","Executive","21–24 Sep","3","₹21,400","Pending","Pending"],
 ["BK-10243","Arjun Mehta","Marina Bay Suites","Suite","18–20 Sep","2","₹8,950","Paid","Completed"],
 ["BK-10242","Sana Iyer","Veranda Grand","Deluxe Room","23–26 Sep","2","₹15,300","Refunded","Cancelled"],
 ["BK-10241","Kiran Shah","The Fern Court","Executive","24–25 Sep","1","₹6,450","Paid","Confirmed"],
];
const tone = (s:string) => s==="Confirmed"||s==="Paid"||s==="Active"||s==="Successful"||s==="Approved"||s==="Refunded"?"success":s==="Pending"||s==="Requested"?"warning":s==="Cancelled"||s==="Failed"||s==="Rejected"?"danger":"neutral" as const;

export function BookingsPage(){return <><PageIntro title="Booking Management" description="Search, review, and manage every reservation." actions={<Button><Plus/>New Booking</Button>}/><FilterBar fields={["Booking ID","Customer","Hotel","Check-in date","Check-out date","Booking status"]}/><Card><CardHead title="Bookings" subtitle="2,845 reservations"/><TableWrap><thead><tr>{["Booking ID","Customer","Hotel / Room","Dates","Guests","Amount","Payment","Status","Actions"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{rows.map(r=><tr key={r[0]} className="hover:bg-muted/30"><Td className="font-medium">{r[0]}</Td><Td>{r[1]}</Td><Td><b className="block font-medium">{r[2]}</b><small className="text-muted-foreground">{r[3]}</small></Td><Td>{r[4]}</Td><Td>{r[5]}</Td><Td className="font-medium">{r[6]}</Td><Td><StatusBadge tone={tone(r[7])}>{r[7]}</StatusBadge></Td><Td><StatusBadge tone={tone(r[8])}>{r[8]}</StatusBadge></Td><Td><div className="flex gap-1"><Button variant="ghost" size="sm">View</Button><Button variant="ghost" size="sm">Edit</Button><CancelDialog/><Button variant="ghost" size="icon" aria-label="Download invoice"><Download/></Button></div></Td></tr>)}</tbody></TableWrap><Pagination/></Card></>}
function CancelDialog(){return <Dialog><DialogTrigger asChild><Button variant="ghost" size="sm" className="text-destructive">Cancel</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Cancel this booking?</DialogTitle><DialogDescription>This releases the room inventory and starts the applicable refund process.</DialogDescription></DialogHeader><DialogFooter><DialogClose asChild><Button variant="outline">Keep booking</Button></DialogClose><DialogClose asChild><Button variant="destructive">Cancel booking</Button></DialogClose></DialogFooter></DialogContent></Dialog>}

const hotels=[
 ["Grand Palace Hotel","Chennai","186","41","132","Active"],["Marina Bay Suites","Mumbai","154","36","106","Active"],["Azure Residency","Goa","128","28","91","Active"],["Veranda Grand","Bengaluru","205","52","139","Active"],["The Fern Court","Kochi","177","57","58","Maintenance"]
];
export function HotelsPage(){return <><PageIntro title="Hotels & Rooms" description="Manage properties, room inventory, and operating status." actions={<Button><Plus/>Add Hotel</Button>}/><Card><CardHead title="Hotel portfolio" subtitle="42 active properties"/><TableWrap><thead><tr>{["Hotel","Location","Total Rooms","Available","Occupied","Status","Actions"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{hotels.map(r=><tr key={r[0]}><Td className="font-medium">{r[0]}</Td>{r.slice(1,5).map(v=><Td key={v}>{v}</Td>)}<Td><StatusBadge tone={r[5]==="Active"?"success":"warning"}>{r[5]}</StatusBadge></Td><Td><Button variant="outline" size="sm">Manage Rooms</Button></Td></tr>)}</tbody></TableWrap></Card><Card className="mt-4"><CardHead title="Room Types" action={<Button size="sm"><Plus/>Add Room</Button>}/><TableWrap><thead><tr>{["Room Type","Hotel","Total Rooms","Available Rooms","Price / Night","Status"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{[["Deluxe Room","Grand Palace Hotel","64","12","₹5,310","Active"],["Executive Room","Grand Palace Hotel","42","6","₹7,850","Active"],["Royal Suite","Marina Bay Suites","18","3","₹12,500","Active"]].map(r=><tr key={r[0]}>{r.map((v,i)=><Td key={v}>{i===5?<StatusBadge tone="success">{v}</StatusBadge>:v}</Td>)}</tr>)}</tbody></TableWrap></Card></>}

export function RatesPage(){return <><PageIntro title="Rates & Pricing" description="Configure room rates, discounts, taxes, and date-based pricing." actions={<Button><Plus/>Add Rate</Button>}/><Card className="p-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{["Hotel","Room type","Date range","Base price","Weekend price","Seasonal price","Discount","Tax"].map((f,i)=><Field key={f} label={f}>{i<3?<select className={inputClass}><option>{i===0?"Grand Palace Hotel":i===1?"Deluxe Room":"20 Sep – 30 Sep 2026"}</option></select>:<input className={inputClass} defaultValue={["₹5,310","₹6,100","₹6,800","10%","18%"][i-3]}/>}</Field>)}</div><div className="mt-5 flex items-center justify-between border-t border-border pt-5"><div><p className="text-xs text-muted-foreground">Final price</p><p className="font-display text-2xl font-semibold">₹5,638</p></div><Button><Save/>Save Rate</Button></div></Card><Card className="mt-4"><CardHead title="Active rate plans"/><TableWrap><thead><tr>{["Hotel","Room Type","Period","Base","Weekend","Discount","Tax","Final Price"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{[["Grand Palace Hotel","Deluxe Room","20–30 Sep","₹5,310","₹6,100","10%","18%","₹5,638"],["Azure Residency","Executive","01–31 Oct","₹7,200","₹8,400","5%","18%","₹8,071"]].map(r=><tr key={r[0]+r[1]}>{r.map(v=><Td key={v}>{v}</Td>)}</tr>)}</tbody></TableWrap></Card></>}

export function AvailabilityPage(){const dates=["Sep 20","Sep 21","Sep 22","Sep 23","Sep 24","Sep 25","Sep 26"];return <><PageIntro title="Availability" description="Update inventory and manage room blocks across properties." actions={<><Button variant="outline"><CalendarDays/>Select dates</Button><BlockDialog/></>}/><FilterBar fields={["Hotel","Room type"]}/><Card><CardHead title="Room Availability" subtitle="Grand Palace Hotel · September 2026"/><TableWrap><thead><tr><Th>Room Type</Th>{dates.map(d=><Th key={d}>{d}</Th>)}<Th>Action</Th></tr></thead><tbody>{[["Deluxe Room",12,10,8,15,14,9,7],["Executive Room",6,5,7,8,9,6,4],["Suite",3,2,2,4,3,1,0]].map(r=><tr key={r[0]}><Td className="font-medium">{r[0]}</Td>{r.slice(1).map((v,i)=><Td key={i}><span className={`grid size-8 place-items-center rounded ${Number(v)===0?"bg-destructive-soft text-destructive":Number(v)<4?"bg-warning-soft text-warning-foreground":"bg-success-soft text-success"}`}>{v}</span></Td>)}<Td><Button variant="ghost" size="sm">Update</Button></Td></tr>)}</tbody></TableWrap><div className="flex flex-wrap gap-4 p-4 text-xs text-muted-foreground"><span>Green: available</span><span>Amber: low inventory</span><span>Red: sold out / blocked</span></div></Card></>}
function BlockDialog(){return <Dialog><DialogTrigger asChild><Button>Block rooms</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Block selected rooms?</DialogTitle><DialogDescription>Blocked inventory cannot be booked until it is unblocked.</DialogDescription></DialogHeader><DialogFooter><DialogClose asChild><Button variant="outline">Go back</Button></DialogClose><DialogClose asChild><Button variant="destructive">Block rooms</Button></DialogClose></DialogFooter></DialogContent></Dialog>}

export function CouponsPage(){return <><PageIntro title="Coupons & Offers" description="Create and manage promotional codes across your hotel portfolio." actions={<Button><Plus/>Create Coupon</Button>}/><Card><TableWrap><thead><tr>{["Coupon Code","Discount","Applicable Hotels","Valid From","Valid Until","Usage","Status","Actions"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{[["MONSOON20","20%","All Hotels","01 Sep 2026","30 Sep 2026","248 / 500","Active"],["GOA15","15%","Azure Residency","15 Sep 2026","15 Oct 2026","84 / 200","Active"],["WELCOME10","10%","All Hotels","01 Jan 2026","31 Dec 2026","1,294 / ∞","Active"],["SUMMER25","25%","5 Hotels","01 Apr 2026","30 Jun 2026","500 / 500","Expired"]].map(r=><tr key={r[0]}>{r.slice(0,6).map(v=><Td key={v}>{v}</Td>)}<Td><StatusBadge tone={r[6]==="Active"?"success":"neutral"}>{r[6]}</StatusBadge></Td><Td><Button variant="ghost" size="sm">Edit</Button><DeleteCoupon/></Td></tr>)}</tbody></TableWrap><Pagination/></Card></>}
function DeleteCoupon(){return <Dialog><DialogTrigger asChild><Button variant="ghost" size="sm" className="text-destructive">Delete</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Delete this coupon?</DialogTitle><DialogDescription>The code will immediately stop working for new bookings.</DialogDescription></DialogHeader><DialogFooter><DialogClose asChild><Button variant="outline">Keep coupon</Button></DialogClose><DialogClose asChild><Button variant="destructive">Delete coupon</Button></DialogClose></DialogFooter></DialogContent></Dialog>}

export function CancellationsPage(){return <><PageIntro title="Cancellation Management" description="Review requests, approve refunds, and track resolution status."/><FilterBar fields={["Booking ID","Customer","Hotel","Status"]}/><Card><TableWrap><thead><tr>{["Booking ID","Customer","Hotel","Booking Amount","Cancellation Date","Reason","Refund Amount","Status","Action"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{[["BK-10242","Sana Iyer","Veranda Grand","₹15,300","14 Sep 2026","Change of plans","₹13,770","Requested"],["BK-10231","Nitin Das","Azure Residency","₹8,240","13 Sep 2026","Travel disruption","₹8,240","Approved"],["BK-10218","Leena Roy","Marina Bay Suites","₹22,800","12 Sep 2026","Medical emergency","₹22,800","Refunded"],["BK-10202","Dev Patel","Grand Palace Hotel","₹9,600","10 Sep 2026","Late request","₹0","Rejected"]].map(r=><tr key={r[0]}>{r.slice(0,7).map(v=><Td key={v}>{v}</Td>)}<Td><StatusBadge tone={tone(r[7])}>{r[7]}</StatusBadge></Td><Td><Button variant="outline" size="sm">Review</Button></Td></tr>)}</tbody></TableWrap></Card></>}

export function PaymentsPage(){return <><PageIntro title="Payment Management" description="Track collections, pending transactions, failures, and refunds."/><div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-5">{[["Total Payments","₹18,42,500"],["Successful","2,614"],["Pending","83"],["Failed","41"],["Refunded","₹1,26,800"]].map(([n,v])=><Card key={n} className="p-4"><p className="text-xs text-muted-foreground">{n}</p><p className="mt-2 font-display text-xl font-semibold">{v}</p></Card>)}</div><FilterBar fields={["Transaction ID","Booking ID","Payment status"]}/><Card><TableWrap><thead><tr>{["Transaction ID","Booking ID","Customer","Amount","Payment Method","Date","Status"].map(x=><Th key={x}>{x}</Th>)}</tr></thead><tbody>{[["TXN-88921","BK-10245","Rahul Kumar","₹10,620","UPI","15 Sep 2026","Successful"],["TXN-88920","BK-10244","Priya Seshadri","₹21,400","Credit Card","15 Sep 2026","Pending"],["TXN-88919","BK-10243","Arjun Mehta","₹8,950","Net Banking","14 Sep 2026","Successful"],["TXN-88918","BK-10242","Sana Iyer","₹15,300","Credit Card","14 Sep 2026","Refunded"],["TXN-88917","BK-10241","Kiran Shah","₹6,450","UPI","14 Sep 2026","Failed"]].map(r=><tr key={r[0]}>{r.slice(0,6).map(v=><Td key={v}>{v}</Td>)}<Td><StatusBadge tone={tone(r[6])}>{r[6]}</StatusBadge></Td></tr>)}</tbody></TableWrap><Pagination/></Card></>}

export function ReportsPage(){return <><PageIntro title="Booking Reports" description="Analyze portfolio performance and export operational reports." actions={<><Button variant="outline"><FileText/>Export CSV</Button><Button><Download/>Export PDF</Button></>}/><FilterBar fields={["Date range","Hotel","Room","Booking status","Payment status"]}/><div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-5">{[["Total Bookings","2,845"],["Total Revenue","₹18,42,500"],["Avg. Booking Value","₹6,476"],["Cancellation Rate","10.8%"],["Occupancy Rate","78.4%"]].map(([n,v])=><Card key={n} className="p-4"><p className="text-xs text-muted-foreground">{n}</p><p className="mt-2 font-display text-xl font-semibold">{v}</p></Card>)}</div><Card><CardHead title="Revenue by Hotel" subtitle="Top five properties"/><div className="space-y-5 p-5">{[["Grand Palace Hotel","₹4,82,500",100],["Marina Bay Suites","₹3,94,200",82],["Azure Residency","₹3,12,800",65],["Veranda Grand","₹2,86,400",59],["The Fern Court","₹2,18,900",45]].map(([n,v,w])=><div key={n as string}><div className="mb-2 flex justify-between text-sm"><span>{n}</span><b>{v}</b></div><div className="h-3 rounded bg-muted"><div className="h-3 rounded bg-primary" style={{width:`${w}%`}}/></div></div>)}</div></Card></>}

function SettingRow({title,description,control}:{title:string;description:string;control:React.ReactNode}){return <div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-b border-border py-4 last:border-0"><div><p className="text-sm font-medium">{title}</p><p className="mt-0.5 text-xs text-muted-foreground">{description}</p></div>{control}</div>}
export function SettingsPage(){const [email,setEmail]=useState(true);return <><PageIntro title="Settings" description="Configure booking rules, cancellations, payments, and notifications." actions={<Button><Save/>Save Changes</Button>}/><div className="grid gap-4 xl:grid-cols-2"><Card><CardHead title="Booking Settings"/><div className="px-5"><SettingRow title="Booking confirmation mode" description="Choose automatic or manual confirmation." control={<select className={inputClass}><option>Automatic</option><option>Manual</option></select>}/><SettingRow title="Minimum stay" description="Minimum nights per reservation." control={<input className={`${inputClass} w-24`} defaultValue="1 night"/>}/><SettingRow title="Maximum stay" description="Maximum nights per reservation." control={<input className={`${inputClass} w-24`} defaultValue="30 nights"/>}/><SettingRow title="Advance booking period" description="How far ahead guests can book." control={<input className={`${inputClass} w-28`} defaultValue="365 days"/>}/></div></Card><Card><CardHead title="Cancellation Settings"/><div className="px-5"><SettingRow title="Cancellation deadline" description="Free cancellation cut-off." control={<input className={`${inputClass} w-28`} defaultValue="48 hours"/>}/><SettingRow title="Cancellation fee" description="Fee after the free period." control={<input className={`${inputClass} w-24`} defaultValue="10%"/>}/><SettingRow title="Refund rules" description="Default policy for approved refunds." control={<select className={inputClass}><option>Original method</option><option>Wallet credit</option></select>}/></div></Card><Card><CardHead title="Payment Settings"/><div className="px-5"><SettingRow title="Payment methods" description="Cards, UPI, and net banking." control={<Switch defaultChecked/>}/><SettingRow title="Deposit percentage" description="Amount required to confirm." control={<input className={`${inputClass} w-24`} defaultValue="25%"/>}/><SettingRow title="Accept pending payments" description="Hold inventory while payment clears." control={<Switch/>}/></div></Card><Card><CardHead title="Notification Settings"/><div className="px-5"><SettingRow title="Booking confirmation email" description="Send when a booking is confirmed." control={<Switch checked={email} onCheckedChange={setEmail}/>}/><SettingRow title="Cancellation email" description="Send cancellation and refund details." control={<Switch defaultChecked/>}/><SettingRow title="Payment notification" description="Notify administrators of failures." control={<Switch defaultChecked/>}/><SettingRow title="Hotel notification" description="Notify properties of booking changes." control={<Switch defaultChecked/>}/></div></Card></div></>}